### PR TITLE
Add Michael + Nick's PhD Thesis

### PR DESCRIPTION
**Pull request by mark-schultz-wu**
Adding links to Nicholas Genise + Michael Walter's PhD thesis on lattice-based cryptography

### CODE REVIEW

**Comment by octaviopk9** [comment]
Hi @mark-schultz, before accepting your PR, could you please confirm that both authors agreed on sharing the respective links of their thesis? Please let us know if they need to be asked and if you could do so. Thanks in advance!

**Comment by mark-schultz-wu** [comment]
I haven't checked with them. Legally speaking they don't need to be asked --- the links are to the University of California's open access reserve of all (sufficiently old to have been uploaded) dissertations iirc.
 
I can check in with them though, and update here when I hear back from them.

**Comment by octaviopk9** [comment]
Hi again Mark,

Thanks for taking the time to do so :)

Although asking for the author's consent is not legally required, we tried to gather them and would suggest keeping it that way. On the one hand, authors may not want to be linked to the project, and it's always better to ask. On the other hand, some authors may have a more recent/updated version of their own thesis and asking them directly gives us the chance to know about that so as to share the latest version.

**Comment by mark-schultz-wu** [comment]
I've checked with both Nick and Michael, and they're both fine with their works being included, and neither mentioned updated versions.

**Pull request merged**
